### ISSUE TITLE
[SOLVED] failed connect to mongodb when i ./start.sh & run node index in workspace bash 

### ISSUE THREAD

**Issue by bangsyir** [nodedock/nodedock#10]
### Info:
- Docker version (`$ docker --version`): 19.03.4
- Nodedock commit (`$ git rev-parse HEAD`): 5b1d93ba34830d6d1db71b49608bc4c89179f194
- System info (Mac, PC, Linux): Linux
- System info disto/version: Xubuntu 18.04 LTS

### Issue:
i have a problem when i run ./start.sh, the logs show "failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]". this is the same issue when I use workspace bash run "node index.js".  I check the MongoDB is UP. btw this is my NODEDOCK_SERVICES=nginx mongo node workspace.

but no issue when i run "node index.js or nodemon index.js" in my nodejs project root...
any solution for my issue?
_____

### error response:

```
node_1                | 2019-11-03T05:00:43.606643127Z Not Connected to Database ERROR!  { error:
node_1                | 2019-11-03T05:00:43.606681800Z    { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
node_1                | 2019-11-03T05:00:43.606690297Z        at Pool.<anonymous> (/var/www/node_modules/mongodb-core/lib/topologies/server.js:431:11)
node_1                | 2019-11-03T05:00:43.606696439Z        at Pool.emit (events.js:198:13)
node_1                | 2019-11-03T05:00:43.606720078Z        at connect (/var/www/node_modules/mongodb-core/lib/connection/pool.js:557:14)
node_1                | 2019-11-03T05:00:43.606725330Z        at makeConnection (/var/www/node_modules/mongodb-core/lib/connection/connect.js:39:11)
node_1                | 2019-11-03T05:00:43.606730608Z        at callback (/var/www/node_modules/mongodb-core/lib/connection/connect.js:261:5)
node_1                | 2019-11-03T05:00:43.606737714Z        at Socket.err (/var/www/node_modules/mongodb-core/lib/connection/connect.js:286:7)
node_1                | 2019-11-03T05:00:43.606744977Z        at Object.onceWrapper (events.js:286:20)
node_1                | 2019-11-03T05:00:43.606751825Z        at Socket.emit (events.js:198:13)
node_1                | 2019-11-03T05:00:43.606757834Z        at emitErrorNT (internal/streams/destroy.js:91:8)
node_1                | 2019-11-03T05:00:43.606764686Z        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
node_1                | 2019-11-03T05:00:43.606771119Z        at process._tickCallback (internal/process/next_tick.js:63:19)
node_1                | 2019-11-03T05:00:43.606777413Z      name: 'MongoNetworkError',
node_1                | 2019-11-03T05:00:43.606783650Z      errorLabels: [ 'TransientTransactionError' ],
node_1                | 2019-11-03T05:00:43.606790086Z      [Symbol(mongoErrorContextSymbol)]: {} } }

```

**Comment by shov** [comment]
Use not `localhost` but `mongo` instead. Cause inside of the container it has another IP and the alias. 
`mongodb://mongo:27017/dbname`

**Comment by bangsyir** [comment]
@shov solved, thank you so much
